import = ["~/.config/alacritty/themes/themes/ayu_mirage.toml"]

# material_theme
# okay themes
# github_dark_dimmed
# gruvbox_dark
# gruvbox_material
# marine_dark

[env]
TERM = "xterm-256color"

# Window settings
[window]
decorations = "buttonless"
opacity = 0.7
blur = true
option_as_alt = "Both"


[window.dimensions]
columns = 130
lines = 54

[window.padding]
x = 4
y = 4


[scrolling]
history = 10000

[font]
size = 10

[font.normal]
# family = "MesloLGS Nerd Font Mono" 
# family = "JuliaMono Nerd Font Mono"
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[shell]
# program = "/usr/bin/bash"
program = "/usr/bin/tmux"

